In [3]:
import json
import pandas as pd

with open("following.json", "r") as file:
    following_data = json.load(file)

with open("who_you've_followed.json", "r") as file2:
    facebook_Data = json.load(file2)

In [7]:
following_data.keys()
type(following_data["relationships_following"])

list

In [4]:
facebook_Data.keys()

dict_keys(['following_v3'])

In [8]:
type(facebook_Data["following_v3"])

list

In [9]:
following_data["relationships_following"][0]

{'title': 'olauction',
 'string_list_data': [{'href': 'https://www.instagram.com/_u/olauction',
   'timestamp': 1787711773}]}

In [10]:
facebook_Data["following_v3"][0]

{'name': 'Polymaker', 'timestamp': 1781560591}

In [11]:
following_data["relationships_following"][0]["title"]

'olauction'

In [12]:
facebook_Data["following_v3"][0]["name"]

'Polymaker'

In [13]:
following_df = pd.DataFrame(following_data["relationships_following"])

In [14]:
following_df.head()

            title                                   string_list_data
0       olauction  [{'href': 'https://www.instagram.com/_u/olauct...
1   lindensiegall  [{'href': 'https://www.instagram.com/_u/linden...
2        laineybo  [{'href': 'https://www.instagram.com/_u/lainey...
3         dcsabes  [{'href': 'https://www.instagram.com/_u/dcsabe...
4  sara.juliana.a  [{'href': 'https://www.instagram.com/_u/sara.j...

In [15]:
followingFB_df = pd.DataFrame(facebook_Data["following_v3"])

In [17]:
followingFB_df.head()

               name   timestamp
0         Polymaker  1781560591
1      Fifth Flavor  1776983041
2          Blenders  1771986581
3  Cryptid Robotics  1765935446
4   King's Hawaiian  1758466479

In [19]:
following_df.columns
following_df.shape
following_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             1020 non-null   str
 1   string_list_data  1020 non-null   object
dtypes: object(1), str(1)
memory usage: 28.1+ KB

In [20]:
following_df = following_df[["title"]]

following_df = following_df.rename(
    columns={"title":"account"}
)
following_df.head()

          account
0       olauction
1   lindensiegall
2        laineybo
3         dcsabes
4  sara.juliana.a